### ISSUE TITLE
Probiotics / Psychobiotics

### ISSUE THREAD

**Issue by cblgh** [mwcvitkovic/neuromodulation_modalities#2]
Hello!

Didn't see this described anywhere, so I figure I might drop some references for potential further research. 

Anyway: probiotics combined with prebiotics seems to be a nascent field of research with very cost effective & non-invasive methods of modulating the production of neurotransmitters by altering (for the better) the gut biome's composition through an increased intake of probiotics (live cultures) and prebiotics (undigestable fibers that feed the healthy gut bacteria you want to establish). Apparently 85-90% of serotonin is produced in the gut, with similarly high production of dopamine also stemming from the gut biome.

Additionally, there seem to be studies coming out that are indicating that Alzheimers / Parkinson's in some extent stems from inflammation reaching and affecting the brain, which can have a significant source in a gut biome that's producing lipopolysaccharides, weakening and leaking through the intestine wall and into the bloodstream and eventually causing large-scale inflammation through the release of cytokines.

Useful starting terms:

* [Gut–brain axis — wikipedia](https://en.wikipedia.org/wiki/Gut%E2%80%93brain_axis)
* https://en.wikipedia.org/wiki/Lipopolysaccharide#Health_effects
* The Gut Microbiota and Inflammation: An Overview https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7589951/
* [Psychobiotics](https://en.wikipedia.org/wiki/Psychobiotic)
* https://en.wikipedia.org/wiki/Probiotic#Depression_and_anxiety
* Paper on one promising type of strain of lactic-acid producing bacteria: »Bacillus coagulans MTCC 5856 for the management of major depression with irritable bowel syndrome: a randomised, double-blind, placebo controlled, multi-centre, pilot clinical study» https://pubmed.ncbi.nlm.nih.gov/29997457/ biased ofc cause it's deployed by a producer of a commercialized version of that strain
* »randomized, double-blind, and controlled clinical trial was conducted among 60 AD patients to assess the effects of probiotic supplementation on cognitive function and metabolic status» https://pubmed.ncbi.nlm.nih.gov/27891089/

As I said, it's nascent, which means there aren't that many large-scale studies yet and resources are scattered, so scouring papers is probably likely to turn up better results than Wikipedia. Anyway, a rabbit hole and a potentially easy win wrt changing one's brain chemistry through the gut :3 

n.b. just learning about this field myself so proceed with caution :3

**Comment by mwcvitkovic** [comment]
Thanks so much for reading and for the pointers! Will take a look
